### ISSUE TITLE
手动备份，文件打包

### ISSUE THREAD

**Issue by zakobakasen** [cngege/BackupMap#1]
建议加入手动备份，有时候服务器有特殊情况需要备份，但下次自动备份时间太长了
大量零碎的文件在百度网盘的文件夹自动备份里很容易出问题，如果输出的不是一个文件夹，而是一个文件，那自动上传差文件可以很轻易的发现，没有压缩都可以的

**Comment by cngege** [comment]
已经更新 可以下载尝试一下，记得提前备份一份存档

**Comment by zakobakasen** [comment]
请问是将压缩包里所有的文件全部放到CSR文件夹下后，删除BackUpMap文件夹，启动服务端来使用吗 我看里面有些文件的后缀不是dll

**Comment by zakobakasen** [comment]
谢谢，解决了，只移动dll文件就可以

**Comment by cngege** [comment]
说明一下，非DLL后缀的文件是调试用的不是必须的，方便用户在插件报错的时候快速定位问题。一般更新只需要替换.dll文件,或者全部替换也可以（建议也加上pdb文件）
BackUpMap文件夹中的.ini文件是这个插件的配置文件，如果没有这个文件，在启动插件的时候会弹出窗口，那个窗口就是设置这个配置文件的。如果知道这个配置文件中的每一项的名称及作用是什么，也可以手动创建修改这个文件，避免弹出窗口（部分服务器是面板服之类的，不适合用UI修改，就可以手动创建修改这个配置文件）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cngege/BackupMap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月25日(星期一) 晚上6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cngege/BackupMap] 手动备份，文件打包 (Issue #1)





 
谢谢，解决了，只移动dll文件就可以
