### ISSUE TITLE
插件第二次备份报错

### ISSUE THREAD

**Issue by zakobakasen** [cngege/BackupMap#3]
`C:\Users\Administrator\Desktop\1.16.40.02_Server_V1.5beta\bedrock-server-1.16.40.02>cmd /c "nanolauncher.exe -r -1 -p .\BDSJSRunner.dll .\BDSNetRunner.dll .\trapdoor-0.9.81-1.16.40.2.dll .\bedrock_server.exe" 
{[插件]JS插件平台已装载。
{[插件] Net插件运行平台(社区版)已装载。此平台基于LGPL协议发行。
version=1.16.40.2
Active code page: 65001

  _______ _                   
 |__ __| | |                  
    | |_ __ __ _ _ __ __| | ___ ___ _ __  
    | | '__/ _` | '_ \ / _` |/ _ \ / _ \| '__| 
    | | | | (_| | |_) | (_| | (_) | (_) | |    
    |_|_| \__,_| .__/ \__,_|\___/ \___/|_|    
                | |                            
                |_|                            
  
github:https://github.com/hhhxiao/TrapDoor
License: GPL
trapdoor version: 0.9.81-1.16.40.2
build time: Nov 14 2021 12:14:52
-----------------------------------------------
[CSR] load CSR\AntiBeacon.csr.dll
[AntiBeacon] 请等待版本适配..
[AntiBeacon] 反信标刷物已加载。适用版本：1.16.40.2
[CSR] load CSR\BackupMap.csr.dll
Get Api sendText failed.
Get Api JSErunScript failed.
Get Api JSEfireCustomEvent failed.
Get Api setscoreboardValue failed.
Get Api setServerMotd failed.
Get Api getscoreById failed.
Get Api setscoreById failed.
Get Api postTick failed.
Get Api getItemRawname failed.
Get Api readHardMemory failed.
Get Api writeHardMemory failed.
[BackupMap] 自动存档备份组件已加载。
[CSR] load CSR\BehavoirLogV2.csr.dll
[Behavior]行为日志已装载！
[CSR] load CSR\BlackBE.csr.dll
[BlackBE] Loaded.
[CSR] load CSR\WsFakePlayer.csr.dll
ws://127.0.0.1:11451
[WsFakePlayer] Loaded.
读取JS文件：.\js\Easychat.js
读取JS文件：.\js\shamplayer.js
sham player >> 假人插件加载完成
NO LOG FILE! - setting up server logging...
[2022-03-31 09:36:25 INFO] Starting Server
[2022-03-31 09:36:25 INFO] Version 1.16.40.2
[2022-03-31 09:36:25 INFO] Session ID 72b83c06-fe8e-4784-a9e4-b0e00d83a579
[2022-03-31 09:36:25 INFO] Level Name: server-property
[2022-03-31 09:36:25 INFO] Game mode: 0 Survival
[2022-03-31 09:36:25 INFO] Difficulty: 3 HARD
[WsFakePlayer] Connect to server success.
[2022-03-31 09:36:25 INFO] opening worlds/server-property/db
[2022-03-31 09:36:28 INFO] IPv4 supported, port: 30101
[2022-03-31 09:36:28 INFO] IPv6 supported, port: 30102
[2022-03-31 09:36:28 INFO] IPv4 supported, port: 19132
[2022-03-31 09:36:28 INFO] IPv6 supported, port: 19133
[2022-03-31 09:36:28 INFO] Server started.
[INFO] trapdoor init finish, server start.
No targets matched selector
No targets matched selector
No targets matched selector
[2022-03-31 09:36:47 INFO] Player connected: tieji, xuid: -6580269050516284592
[BlackBE] [INFO] 对tieji的云黑检测成功.
[2022-03-31 09:36:55 BackupMap ]5S后开始备份存档
Saving...
The command is already running
已获取备份文件列表，准备备份
存档全部复制成功
There are 1/30 players online:
tieji
[2022-03-31 09:37:36 BackupMap ]5S后开始备份存档
The command is already running
The command is already running
已获取备份文件列表，准备备份
System.IO.IOException: 文件“plugins\BackUpMap\tmp\server-property\db\2564122.ldb”已经存在。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   在 BackupMap.AutoBackup.BackupDB(String list, String savepath)
因备份失败而终止
[2022-03-31 09:37:41 INFO] Server stop requested.
[2022-03-31 09:37:41 INFO] Stopping server...`

请问这个怎么解决啊
备份报错之后 关服也关不掉了
存档和服务端已经打包好了 如果需要的话可以发给您
谢谢

**Comment by cngege** [comment]
System.IO.IOException: 文件“plugins\BackUpMap\tmp\server-property\db\2564122.ldb”已经存在。
检测看看是否因为权限不足导致第一次备份后删除临时文件失败？
tmp文件夹内的文件为临时文件，打包备份会将存档复制到这个文件夹内，用以判断是否将存档中的每个文件都备份成功
看你的报错信息，原因应该就是，第一次备份后没有能自动删除tmp中的临时文件
（关闭打包备份可以临时规避这个问题）
